version: '3.7'
services:
  mailer_mongo_db:
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    restart: always
    volumes:
      - /Users/andrz/Documents/Volumes/mailer-mongo-volume:/data/db
    networks: 
      - mailer
  mailer_service:
    build: ./
    restart: always
    volumes:
      - ./:/usr/src/api/
    links:
      - mailer_mongo_db
    ports:
      - 3000:3000
      - 465:465
    env_file: ./.env
    command: 'npm start'
    networks: 
      - mailer

networks:
  mailer:
    driver: bridge
