version: '3.7'
services:
  mailer_mongo_db:
    container_name: mailer-db
    image: mongo:4
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=admin
      - MAILER_USERNAME=$MONGO_USERNAME
      - MAILER_PWD=$MONGO_PASSWORD
      - MAILER_DATABASE=$MONGO_DBNAME
    ports:
      - 27017:27017
    restart: always
    volumes:
      #- db-data:/data/db
      #- /Users/andrz/Documents/Volumes/mailer-mongo-volume:/data/db
      - ./docker-entrypoint/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks: 
      - mailer
  api:
    container_name: mailer-api
    build: 
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/usr/src/api/
    depends_on:
      - mailer_mongo_db
    ports:
      - 3000:3000
      - 465:465
    env_file: ./.env
    command: 'npm start'
    networks: 
      - mailer

networks:
  mailer:
    driver: bridge

volumes:
  db-data: