version: '3.7'
services:

  mailer_mongo_db:
    container_name: mailer-db
    image: mongo:4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=admin
      - MAILER_USERNAME=$MONGO_USERNAME
      - MAILER_PWD=$MONGO_PASSWORD
      - MAILER_DATABASE=$MONGO_DBNAME
    ports:
      - 27017:27017
    volumes:
      #- db-data:/data/db
      #- /Users/andrz/Documents/Volumes/mailer-mongo-volume:/data/db
      - ./.docker/mongodb/docker-entrypoint/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks: 
      - mailer

  api:
    container_name: mailer-api
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/api/
    depends_on:
      - mailer_mongo_db
      - rabbit_mq
    ports:
      - 3000:3000
      - 465:465
    command: 'npm start'
    networks: 
      - mailer

  rabbit_mq:
    container_name: rabbitmq
    image: rabbitmq:3.8.7-management-alpine
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/mnesia/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - mailer

networks:
  mailer:
    driver: bridge

volumes:
  db-data: